### ISSUE TITLE
Does not seem to work on Cassandra 3

### ISSUE THREAD

**Issue by anders16000** [adejanovski/cassandra-jdbc-wrapper#1]
Hello.
We receive an error message: "unconfigured table schema_keyspaces" when trying to connect to cassandra. (we can connect with an older jdbc driver over rpc, without any problems, so there are no problems on the Cassandra side.)

Do you have any plans to support Cassandra 3? 
If thats the case, -whats the time frame?

**Comment by adejanovski** [comment]
Hi,

The current version if the wrapper uses the datastax Java driver 2.1.9, which is indeed not compatible with Cassandra 3.x

I'll work on 3.x compatibility in the 2 coming weeks if time allows.

**Comment by adejanovski** [comment]
The master branch is now compatible with Cassandra 3.x and the fat jar can be downloaded here : https://drive.google.com/open?id=0B7fwX0DqcWSTdmlnZUxYOVVEbFk

Using tuples is broken since some methods disappeared from the Java driver.
I'll see if I can fix this soon.

I'll upload everything to Maven shortly.
